/*
 * User API
 *
 * An API for creating and authenticating system users
 *
 * API version: 0.1.0
 * Contact: joe@bebo.dev
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	goauthapi "github.com/bebo-dot-dev/go-auth-api/go"
)

func main() {
	log.Printf("Server started")

	AuthAPIApiService := goauthapi.NewAuthAPIApiService()
	AuthAPIApiController := goauthapi.NewAuthAPIApiController(AuthAPIApiService)

	router := goauthapi.NewRouter(AuthAPIApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
